# Generated by Django 4.2.9 on 2024-01-03 01:40

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import phonenumber_field.modelfields


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Company",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100)),
                ("address", models.CharField(blank=True, max_length=255)),
                ("industry", models.CharField(blank=True, max_length=100)),
                (
                    "phone_number",
                    phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region="US"),
                ),
                ("website", models.URLField(blank=True, null=True)),
                ("employer", models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name="Recruiter",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=200)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                (
                    "phone_number",
                    phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region="US"),
                ),
                ("is_independent", models.BooleanField()),
                ("company", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="interviews.company")),
            ],
        ),
        migrations.CreateModel(
            name="Job",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("job_url", models.URLField(blank=True, null=True)),
                ("posted_date", models.DateTimeField(auto_now_add=True)),
                ("applied_online", models.BooleanField()),
                ("company", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="interviews.company")),
                (
                    "recruiter",
                    models.ForeignKey(
                        null=True, on_delete=django.db.models.deletion.SET_NULL, to="interviews.recruiter"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Interview",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("purpose", models.CharField(max_length=200)),
                ("date", models.DateTimeField()),
                ("virtual_link", models.URLField(blank=True, null=True)),
                ("attendees", models.ManyToManyField(blank=True, to="interviews.recruiter")),
                ("job", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="interviews.job")),
            ],
        ),
        migrations.CreateModel(
            name="CommunicationLog",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("date", models.DateField(default=django.utils.timezone.now)),
                ("log_entry", models.TextField()),
                (
                    "log_type",
                    models.CharField(
                        choices=[
                            ("EM", "E-mail"),
                            ("LI", "LinkedIn Message"),
                            ("PC", "Phone call"),
                            ("ZC", "Zoom call"),
                        ],
                        default="EM",
                        max_length=2,
                    ),
                ),
                (
                    "job",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="interviews.job"
                    ),
                ),
                (
                    "recruiter",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="interviews.recruiter"),
                ),
            ],
        ),
    ]
