# Generated by Django 4.2.9 on 2024-01-10 02:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("interviews", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="communicationlog",
            name="comms_type",
            field=models.CharField(
                choices=[("EM", "E-mail"), ("LI", "LinkedIn Message"), ("PC", "Phone call"), ("ZC", "Zoom call")],
                default="EM",
                max_length=2,
            ),
        ),
    ]
