# Generated by Django 4.2.9 on 2024-01-10 02:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("interviews", "0002_communicationlog_comms_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="communicationlog",
            name="comms_type",
            field=models.CharField(
                choices=[
                    ("EM", "E-mail"),
                    ("LI", "LinkedIn message"),
                    ("PC", "Phone call"),
                    ("VC", "Video call"),
                    ("TM", "Text message"),
                ],
                default="EM",
                max_length=2,
            ),
        ),
        migrations.AlterField(
            model_name="communicationlog",
            name="log_type",
            field=models.CharField(
                choices=[
                    ("EM", "E-mail"),
                    ("LI", "LinkedIn message"),
                    ("PC", "Phone call"),
                    ("VC", "Video call"),
                    ("TM", "Text message"),
                ],
                default="EM",
                max_length=2,
            ),
        ),
    ]
