# Generated by Django 4.2.1 on 2023-06-28 06:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("intertraq", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="communicationlog",
            name="date",
            field=models.DateField(auto_now=True),
        ),
    ]
