# Generated by Django 4.2.2 on 2023-06-28 06:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("intertraq", "0004_alter_communicationlog_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="job_url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
